# Generated by Django 4.2 on 2023-10-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_alter_category_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="products/%Y/%B/%d/"),
        ),
    ]
